server:
  port: 7003
rpc:
  name: khr123
  version: 1.0
  serverPort: 8083
  serializer: JdkSerializer
  registryConfig:
    registry: EtcdRegistry

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.117.123.182:8848
  application:
    name: order-service
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 47.117.123.182:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
  service:
    vgroup-mapping:
      seata-demo: default
  data-source-proxy-mode: AT
  tx-service-group: seata-demo

