server:
  port: 7003
rpc:
  name: khr123
  version: 1.0
  serverPort: 8083
  serializer: JdkSerializer
  registryConfig:
    registry: RedissonRegistry

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver



